import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useSession } from 'next-auth/react'
import Chat from '@/components/Chat'
import Login from '@/components/Login'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session, status } = useSession()

  return (
    <div className='h-[100vh]'>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* lets decide wheather its LOGIN or CHAT */}
      {session
        ? <h1><Chat /></h1> 
        : <h1><Login/></h1>
      }
    </div>
  )
}
